; HKEY_CURRENT_USER\Keyboard layout\Preload

[LAYOUTS]
00000409=en,us,English,`1234567890-=qwertyuiop[]\asdfghjkl;'zxcvbnm,./~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?
a0000409=en,us,English,`1234567890-=qwertyuiop[]\asdfghjkl;'zxcvbnm,./~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?
00000809=en,uk,UK,`1234567890-=qwertyuiop[]#asdfghjkl;'zxcvbnm,./¬!"£$%^&*()_+QWERTYUIOP{}~ASDFGHJKL:@ZXCVBNM<>?\|¦€éúíóáÉÚÍÓÁ
00001809=en,ir,Irish, 1234567890-=qwertyuiop[]#asdfghjkl;'zxcvbnm,./¬!"£$%^&*()_+QWERTYUIOP{}~ASDFGHJKL:@ZXCVBNM<>?\|¦`€éúíóáÉÚÍÓÁèùìòàÈÙÌÒÀ
00010409=en,dv,Dvorak,`1234567890[]',.pyfgcrl/=\aoeuidhtns-;qjkxbmwvz~!@#$%^&*(){}"<>PYFGCRL?+|AOEUIDHTNS_:QJKXBMWVZ
00030409=en,dvl,Dvorak for left hand,`[]/pfmlj4321;qbyurso.65=\-kcdtheaz87'xgvwni,09~{}?PFMLJ$#@!:QBYURSO>^%+|_KCDTHEAZ*&"XGVWNI<)(
00040409=en,dvr,Dvorak for right hand,`1234jlmfp/[]56q.orsuyb;=\78zaehtdck-90x,inwvg'~!@#$JLMFP?{}%^Q>ORSUYB:+|&*ZAEHTDCK_()X<INWVG"
00020409=en,usx,US (International), 1234567890-=qwertyuiop[]\asdfghjkl; zxcvbnm,./ !@#$% &*()_+QWERTYUIOP{}|ASDFGHJKL: ZXCVBNM<>?
;00020409=en,usx,US (International), 1234567890-=qwertyuiop[]\asdfghjkl; zxcvbnm,./ !@#$% &*()_+QWERTYUIOP{}|ASDFGHJKL: ZXCVBNM<>?¡²€¼½¾‘’¥×äåé®þúíóö«»¬áßðø¶´æ©ñµç¿¹£÷ÄÅÉÞÜÚÍÓÖ¦Á§ÐØ°¨Æ¢ÑÇèùìòàÈÙÌÒÀÕÃÑýÝ
a0000809=en,dv,Dvorak,`1234567890[]',.pyfgcrl/=\aoeuidhtns-;qjkxbmwvz~!@#$%^&*(){}"<>PYFGCRL?+|AOEUIDHTNS_:QJKXBMWVZ

00000419=ru,ru,Ðóññêàÿ,¸1234567890-=éöóêåíãøùçõú\ôûâàïðîëäæýÿ÷ñìèòüáþ.¨!"¹;%:?*()_+ÉÖÓÊÅÍÃØÙÇÕÚ/ÔÛÂÀÏÐÎËÄÆÝß×ÑÌÈÒÜÁÞ,
a0000419=ru,ru,Ðóññêàÿ,¸1234567890-=éöóêåíãøùçõú\ôûâàïðîëäæýÿ÷ñìèòüáþ.¨!"¹;%:?*()_+ÉÖÓÊÅÍÃØÙÇÕÚ/ÔÛÂÀÏÐÎËÄÆÝß×ÑÌÈÒÜÁÞ,
00010419=ru,ru,Ðóññêàÿ (ìàøèíîïèñü),|¹-/":,._?%!;éöóêåíãøùçõú)ôûâàïðîëäæýÿ÷ñìèòüáþ¸+1234567890=\ÉÖÓÊÅÍÃØÙÇÕÚ(ÔÛÂÀÏÐÎËÄÆÝß×ÑÌÈÒÜÁÞ¨
00010440=ru,ru,Ðóññêàÿ,¸1234567890-=éöóêåíãøùçõú\ôûâàïðîëäæýÿ÷ñìèòüáþ.¨!"¹;%:?*()_+ÉÖÓÊÅÍÃØÙÇÕÚ/ÔÛÂÀÏÐÎËÄÆÝß×ÑÌÈÒÜÁÞ,
01030419=ru,ru,Ðóññêàÿ,¸1234567890-=éöóêåíãøùçõú\ôûâàïðîëäæýÿ÷ñìèòüáþ.¨!"¹;%:?*()_+ÉÖÓÊÅÍÃØÙÇÕÚ/ÔÛÂÀÏÐÎËÄÆÝß×ÑÌÈÒÜÁÞ,
00000422=ua,ua,Óêðà¿íñüêà,¸1234567890-=éöóêåíãøùçõ¿\ô³âàïðîëäæºÿ÷ñìèòüáþ.¨!"¹;%:?*()_+ÉÖÓÊÅÍÃØÙÇÕ¯/Ô²ÂÀÏÐÎËÄÆªß×ÑÌÈÒÜÁÞ,'´¥
00020422=ua,ua,Óêðà¿íñüêà,¸1234567890-=éöóêåíãøùçõ¿\ô³âàïðîëäæºÿ÷ñìèòüáþ.¨!"¹;%:?*()_+ÉÖÓÊÅÍÃØÙÇÕ¯/Ô²ÂÀÏÐÎËÄÆªß×ÑÌÈÒÜÁÞ,'´¥
a0000422=ua,ua,Óêðà¿íñüêà,'1234567890-=éöóêåíãøùçõ¿´ô³âàïðîëäæºÿ÷ñìèòüáþ.’!"¹;%:?*()_+ÉÖÓÊÅÍÃØÙÇÕ¯¥Ô²ÂÀÏÐÎËÄÆªß×ÑÌÈÒÜÁÞ,\/
a0010422=ua,ua,Óêðà¿íñüêà,'1234567890-=éöóêåíãøùçõ¿\ô³âàïðîëäæºÿ÷ñìèòüáþ.’!"¹;%:?*()_+ÉÖÓÊÅÍÃØÙÇÕ¯/Ô²ÂÀÏÐÎËÄÆªß×ÑÌÈÒÜÁÞ,´¥
00000423=blr,blr,Áåëîðóññêàÿ,¸1234567890-=éöóêåíãø¢çõ'\ôûâàïðîëäæýÿ÷ñì³òüáþ.¨!"¹;%:?*()_+ÉÖÓÊÅÍÃØ¡ÇÕ'/ÔÛÂÀÏÐÎËÄÆÝß×ÑÌ²ÒÜÁÞ,

00000406=da,da,Danish,½1234567890+ qwertyuiopå 'asdfghjklæøzxcvbnm,.-§!"#¤%&/()=? QWERTYUIOPÅ *ASDFGHJKLÆØZXCVBNM;:_<>@£$€{[]}|€\µõãñÕÃÑéýúíóáÁÉÝÚÍÓèùìòàÈÙÌÒÀëÿüïöäËÜÏÖÄêûîôâÊÛÎÔÂ
00000407=de,gr,German, 1234567890ß qwertzuiopü+#asdfghjklöäyxcvbnm,.-°!"§$%&/()=? QWERTZUIOPÜ*'ASDFGHJKLÖÄYXCVBNM;:_<>²³{[]}\@€~|µêûîôâÊÛÎÔÂéúíóáýÉÚÍÓÁÝèùìòàÈÙÌÒÀ
00010407=de,gr1,German (IBM), 1234567890ß qwertzuiopü+#asdfghjklöäyxcvbnm,.-°!"§$%&/()=? QWERTZUIOPÜ*'ASDFGHJKLÖÄYXCVBNM;:_<>²³{[]}\@€~|µêûîôâÊÛÎÔÂéúíóáýÉÚÍÓÁÝèùìòàÈÙÌÒÀ
0000040f=ic,ic,Icelandic, 1234567890ö-qwertyuiopð'+asdfghjklæ zxcvbnm,.þ !"#$%&/()=Ö_QWERTYUIOPÐ?*ASDFGHJKLÆ'ZXCVBNM;:Þ<>°€{[]}\@€~|µêûîôâÊÛÎÔÂèùìòàÈÙÌÒÀéýúíóáÉÝÚÍÓÁëÿüïöäËÜÏÖÄåÅ

0000040c=fr,fr,French,²&é"'(-è_çà)=azertyuiop $*qsdfghjklmùwxcvbn,;:! 1234567890°+AZERTYUIOP £µQSDFGHJKLM%WXCVBN?./§<>#{[|\^@]}€¤ãõñÃÕÑàèùìòÀÈÙÌÒâêûîôÂÊÛÎÔäëÿüïöÄËÜÏÖ
0000080c=fr,be,Belgian French,²&é"'(§è!çà)-azertyuiop $µqsdfghjklmùwxcvbn,;:=³1234567890°_AZERTYUIOP *£QSDFGHJKLM%WXCVBN?./+<>|@#^{}€[]\âêûîôÂÊÛÎÔäëÿüïöÄËÜÏÖáéýúíóÁÉÝÚÍÓàèùìòÀÈÙÌÒãõñÃÕÑ
0000100c=fr,sf,Swiss French,§1234567890' qwertzuiopè $asdfghjkléàyxcvbnm,.-°+"*ç%&/()=? QWERTZUIOPü £ASDFGHJKLöäYXCVBNM;:_<>¦@#°§¬|¢€[]{}\êûîôâÊÛÎÔÂëüïöäËÜÏÖÄèùìòàÈÙÌÒÀéúíóáýÉÚÍÓÁÝõãñÕÃÑ
00000c0c=fr,fc,Canadian French (Legacy),°1234567890-=qwertyuiop çàasdfghjkl;èzxcvbnm,.é°!"#$%?&*()_+QWERTYUIOP ÇÀASDFGHJKL:ÈZXCVBNM'.ÉùÙ¬¹@³¼½¾{[]}|¶¥øþæßðª\«»¢µ<>/¡²£¤±ØÞÆ§Ð|êûîôâÊÛÎÔÂçÇõãñÕÃÑéýúíóáÉÝÚÍÓÁèùìòàÈÙÌÒÀëÿüïäËÜÏÖÄ
00001009=fr,ca,Canadian French,#1234567890-=qwertyuiop  <asdfghjkl; zxcvbnm,.é|!"/$%?&*()_+QWERTYUIOP  >ASDFGHJKL: ZXCVBNM'.É«»\±@£¢¤¬¦²³¼½¾§¶[]~{}°µ­éýúíóáÉÝÚÍÓÁêûîôâÊÛÎÔÂçÇèùìòàÈÙÌÒÀëÿüöäËÜÏÖÄ
00011009=fr,can,Canadian Multilingual Standard,/1234567890-=qwertyuiop çàasdfghjkl;èzxcvbnm,.é\!@#$%?&*()_+QWERTYUIOP ÇÀASDFGHJKL:ÈZXCVBNM'"ÉùÙ|¤{}[]¬€°«»<>êûîôâÊÛÎÔÂëÿüïöäËŸÜÏÖÄèùìòàÈÙÌÒÀõãñÕÃÑ

00000410=it,it,Italian,\1234567890'ìqwertyuiopè+ùasdfghjklòàzxcvbnm,.-|!"£$%&/()=?^QWERTYUIOPé*§ASDFGHJKLç°ZXCVBNM;:_<>€@#[]{}
00010410=it,it,Italian (142),\1234567890' qwertyuiop + asdfghjkloazxcvbnm,.-|!" $%&/()=?^QWERTYUIOP *§ASDFGHJKL °ZXCVBNM;:_<>€@#[]{}

0000040a=sp,sp,Spanish,º1234567890'¡qwertyuiop +çasdfghjklñ zxcvbnm,.-ª!"·$%&/()=?¿QWERTYUIOP *ÇASDFGHJKLÑ ZXCVBNM;:_<>\|@#€¬[]{}õãÕÃèùìòàÈÙÌÒÀéýúíóáÉÝÚÍÓÁêûîôâÊÛÔÂëÿüïöäËÜÖÄ
0000080a=sp,la,Latin American,|1234567890'¿qwertyuiop +}asdfghjklñ{zxcvbnm,.-°!"#$%&/()=?¡QWERTYUIOP *]ASDFGHJKLÑ[ZXCVBNM;:_<>¬\@~êûîôâÊÛÎÔÂèùòàÈÌÒÀéýúíóáÉÝÚÍÓÁëÿüïöäËÜÏÖÄ
0000200a=sp,la,Latin American,|1234567890'¿qwertyuiop +}asdfghjklñ{zxcvbnm,.-°!"#$%&/()=?¡QWERTYUIOP *]ASDFGHJKLÑ[ZXCVBNM;:_<>¬\@~êûîôâÊÛÎÔÂèùòàÈÌÒÀéýúíóáÉÝÚÍÓÁëÿüïöäËÜÏÖÄ
0000040a=sp,es,Spanish Variation,'1234567890- qwertyuiop÷  asdfghjklñçzxcvbnm,.=·ª"/()¡!¿? + QWERTYUIOP×  ASDFGHJKLÑÇZXCVBNM;:%<>\|@#¼½¬_#§\*€[]$&@[]|£±~{}õãÕÃêûîôâÊÛÎÔÂëÿüïöäËÜÏÖÄèùìòàÈÙÌÒÀéýúíóáÉÚÍÓÁ


a0000c0a=sp,sp,Spanish Dvorak,º1234567890'¡.,ñpyfgchl + aoeuidrtns -qjkxbmwvzª!"·$%&/()=?¿:;ÑPYFGCHL *ÇAOEUIDRTNS _QJKXBMWVZ<>\|@#~€¬[]{}    èùìòàÈÙÌÒÀéýúíóáÉÝÚÍÓÁêûîôâÊÛÔÂëÿüïöäËÜÖÄ



00000414=no,no,Norwegian,|1234567890+\qwertyuiopå 'asdfghjkløæzxcvbnm,.-§!"#¤%&/()=? QWERTYUIOPÅ *ASDFGHJKLØÆZXCVBNM;:_<>@£$€{[]}€µéýúíóáÉÝÚÍÓÁõãñÕÃÑëÿüïöäËÜÏÖÄèùìòàÈÙÌÒÀêûîôâÊÛÎÔÂ
0000041d=se,se,Swedish,§1234567890+ qwertyuiopå 'asdfghjklöäzxcvbnm,.-½!"#¤%&/()=? QWERTYUIOPÅ *ASDFGHJKLÖÄZXCVBNM;:_<>@£$€{[]}\|µõãñÕÃÑéýúíóáÉÝÚÍÓÁëÿüïöäËÜÏÖÄèùìòàÈÙÌÒÀêûîôâÊÛÎÔÂ
0000040b=fi,fi,Finnish,§1234567890+ qwertyuiopå 'asdfghjklöäzxcvbnm,.-½!"#¤%&/()=? QWERTYUIOPÅ *ASDFGHJKLÖÄZXCVBNM;:_<>@£$€{[]}\|µõãñÕÃÑéýúíóáÉÝÚÍÓÁëÿüïöäËÜÏÖÄèùìòàÈÙÌÒÀêûîôâÊÛÎÔÂ

00000813=nl,be,Belgian Dutch,²&é"'(§è!çà)-azertyuiop $µqsdfghjklmùwxcvbn,;:=³1234567890°_AZERTYUIOP *£QSDFGHJKLM%WXCVBN?./+<>|@#^{}€[]\âêûîôÂÊÛÎÔäëÿüïöÄËÜÏÖáéýúíóÁÉÝÚÍÓàèùìòÀÈÙÌÒãõñÃÕÑ
0001080c=nl,be,Belgian Dutch,²&é"'(§è!çà)-azertyuiop $µqsdfghjklmùwxcvbn,;:=³1234567890°_AZERTYUIOP *£QSDFGHJKLM%WXCVBN?./+<>|@#^{}€[]\âêûîôÂÊÛÎÔäëÿüïöÄËÜÏÖáéýúíóÁÉÝÚÍÓàèùìòÀÈÙÌÒãõñÃÕÑ
00000816=po,po,Portuguese,\1234567890'«qwertyuiop+  asdfghjklçºzxcvbnm,.-|!"#$%&/()=?»QWERTYUIOP*  ASDFGHJKLÇªZXCVBNM;:_<>@£§€{[]}ëÿüïöäËÜÏÖÄéýúíóáÉÝÚÍÓÁõãñÕÃÑèùìòàÈÙÌÒÀêûîôâÊÛÎÔÂ
00000416=po,br,Brazil ABNT,'1234567890-=qwertyuiop []asdfghjklç zxcvbnm,.;"!@#$% &*()_+QWERTYUIOP {}ASDFGHJKLÇ ZXCVBNM<>:\/|?éýúíóáõãñèùìòàêûîôâëÿüïöäÉÝÚÍÓÁÕÃÑÈÙÌÒÀÊÛÎÔÂËÜÏÖÄ¹²³£¢¬§°ªº°
00010416=po,br,Brazil ABNT,'1234567890-=qwertyuiop []asdfghjklç zxcvbnm,.;"!@#$% &*()_+QWERTYUIOP {}ASDFGHJKLÇ ZXCVBNM<>:\/|?éýúíóáõãñèùìòàêûîôâëÿüïöäÉÝÚÍÓÁÕÃÑÈÙÌÒÀÊÛÎÔÂËÜÏÖÄ¹²³£¢¬§°ªº°
a0000416=po,br,Dvorak-Br Shifted,"!@#$% &*(){}?,.pyfgcrl´=aoeuidhtns~-ç;qjkxbmwvz\1234567890[]/<>PYFGCRL`+AOEUIDHTNS^_Ç:QJKXBMWVZ|
a0030416=po,br,Dvorak-Br Shifted,"!@#$% &*(){}?,.pyfgcrl´=aoeuidhtns~-ç;qjkxbmwvz\1234567890[]/<>PYFGCRL`+AOEUIDHTNS^_Ç:QJKXBMWVZ|

00000405=cz,cz,Czech,;+ìšèøžýáíé= qwertzuiopú) asdfghjklù§yxcvbnm,.- 1234567890% QWERTZUIOP/('ASDFGHJKL"!YXCVBNM?:_\|éàŸúíóáœåýæñÉÀÚÍÓÁŒÅÝÆÑùÙìøžšï¾èòÌØŽŠÏ¼ÈÒ~\|€'÷×ðÐ[]³£$ß¤<>#@{}*îôâÎÔÂãÃê¹Ê¥¿¯ûõÛÕëüöäËÜÖÄþºçÞªÇ
0000041b=sk,sk,Slovak,;+¾šèžýáíé= qwertzuiopúäòasdfghjklô§yxcvbnm,.- 1234567890% QWERTZUIOP/()ASDFGHJKL"!YXCVBNM?:_&*éàŸúíóáœåýæñÉÀÚÍÓÁŒÅÝÆÑùÙìøžšï¾èòÌØŽŠÏ¼ÈÒ~\|€'÷×ðÐ[]³£$ß¤<>#@{}`îôâÎÔÂãÃê¹Ê¥¿¯ûõÛÕüöäÜÖÄþºçÞªÇ
0001041b=sk,sk,Slovak (QWERTY),;+¾šèžýáíé= qwertyuiopúäòasdfghjklô§zxcvbnm,.- 1234567890% QWERTZUIOP/()ASDFGHJKL"!YXCVBNM?:_&*éàŸúíóáœåýæñÉÀÚÍÓÁŒÅÝÆÑùÙìøžšï¾èòÌØŽŠÏ¼ÈÒ~\|€'÷×ðÐ[]³£$ß¤<>#@{}`îôâÎÔÂãÃê¹Ê¥¿¯ûõÛÕüöäÜÖÄþºçÞªÇ
00000424=si,si,Slovenian, 1234567890'+qwertzuiopšðžasdfghjklèæyxcvbnm,.- !"#$%&/()=?*QWERTZUIOPŠÐŽASDFGHJKLÈÆYXCVBNM;:_<>ºçªÇëüöäËÜÖÄ~`\|€÷×[]³£ß¤@{}§ìøžšï¾èòÌØŽŠÏ¼ÈÒîôâÎÔÂãÃùÙê¹Ê¥¿¯éàŸúíóáœåýæñÉÀÚÍÓÁŒÅÝÆÑûõÛÕ
00000418=ro,ro,Romanian,]1234567890+'qwertzuiopãîâasdfghjklºþyxcvbnm,.-[!"#¤%&/()=?*QWERTZUIOPÃÎÂASDFGHJKLªÞYXCVBNM;:_<>~¡^¢°²`·´½¨¸\|÷×ðÐ³£$ß{}§

00000415=pl,pl,Polish,`1234567890-=qwertyuiop[]\asdfghjkl;'zxcvbnm,./ !@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?|êó¹œ³¿ŸæñÊÓ¥Œ£¯ÆÑê€ó¹œ³¿Ÿæñ
00010415=pl,pl214,Polish (214), 1234567890+'qwertzuiop¿œóasdfghjkl³¹yxcvbnm,.- !"#¤%&/()=?*QWERTZUIOPñæŸASDFGHJKL£êYXCVBNM;:_<>Ê¥¿¯~`\¦€÷×ðÐ$ß¤@{}§ìøžšïèòÌØŽŠÏÈÒîôâÎÔÂãÃùÙéàúíáýÉÀÚÍÓÁŒÝÆÑûõÛÕëüöäËÜÖÄ

0000040e=hu,hu,Hungarian,0123456789öüóqwertzuiopõúûasdfghjkléáyxcvbnm,.-§'"+!%/=()ÖÜÓQWERTZUIOPÕÚÛASDFGHJKLÉÁYXCVBNM?:_íÍ~`\|Ä€÷×äðÐ[]³£$ß¤<>#&@{};*ìøžšïèòÌØŽŠÏÈÒîôâÎÔÂãÃùÙê¹Ê¥¿¯àŸíœåýæñÀÍŒÅÝÆÑëËþºçÞªÇ
0001040e=hu,hu101,Hungarian (101 keys),í123456789öüóqwertyuiopõúûasdfghjkléázxcvbnm,.-Í'"+!%/=()ÖÜÓQWERTYUIOPÕÚÛASDFGHJKLÉÁZXCVBNM?:_íÍ0~¡^¢°²`ÿ´½\|Ä§¤€÷×äðÐ[]³£$ß<>#&@{};*

00000402=bg,bg,Bulgarian,`1234567890-.,óåèøùêñäçö;(üÿàîæãòíâì÷þéúýôõïðëá~!?+"%=:/_¹²VûÓÅÈØÙÊÑÄÇÖ§)ÜßÀÎÆÃÒÍÂÌ×ÞÉÚÝÔÕÏÐËÁ
00010402=en,us,Bulgarian (Latin),`1234567890-=qwertyuiop[]\asdfghjkl;'zxcvbnm,./~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?
00030402=bg,bg,Bulgarian,(1234567890-.,óåèøùêñäçö;„üÿàîæãòíâì÷þéúýôõïðëá)!?+"%=:/–¹$ˆûÓÅÈØÙÊÑÄÇÖ§“?ßÀÎÆÃÒÍÂÌ×ÞÉÚÝÔÕÏÐËÁ
-00000402=bg,bg,Bulgarian (Phonetic),÷1234567890-=ÿâåðòúóèîïøùþàñäôãõéêë;'çüöæáíì,./×!@#$%^&*()_+ßÂÅÐÒÚÓÈÎÏØÙÞÀÑÄÔÃÕÉÊË:"ÇÜÖÆÁÍÌ<>?

00000425=et,et,Estonian, 1234567890+ qwertyuiopüõ'asdfghjklöäzxcvbnm,.- !"#¤%&/()=? QWERTYUIOPÜÕ*ASDFGHJKLÖÄZXCVBNM;:_<>@£$€{[]}\§½|^þðèÞÐÈéóúêãñÉÓÚÊÃÑõÕ
00000426=lv,lv,Latvian,`1234567890-=qwertyuiop[] asdfghjkl;'zxcvbnm,./ !@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?\|­«»€’–çºûîõâðìíïþèò§°±×—ÇªÛÎÕÂÐÌÍÏÞÈÒéóúêãñÉÓÚÊÃÑüöäÜÖÄëåýËÅÝ
00000427=lt,lt,Lithuanian,`àèæëáðøû90-þqwertyuiop[]\asdfghjkl;'zxcvbnm,./~ÀÈÆËÁÐØÛ()_ÞQWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?\|1234567890=€!@#$%^&*+

0000082c=az,az,Azeri Cyrillic,`1234567890-=¼ óêåíãø çõ \ôûâàïðîëäæ  ÷ñìèò á .~!"¹;%:?*()_+£ ÓÊÅÍÃØ ÇÕ /ÔÛÂÀÏÐÎËÄÆ  ×ÑÌÈÒ Á ,
0000042c=azl,azl,Azeri Latin,`1234567890-=qüertyuiopöð\asdfghjklý zxcvbnmçþ.~!" ;%:?*()_+QÜERTYUÝOPÖÐ/ASDFGHJKLI ZXCVBNMÇÞ

00000843=uzb,uzb,Uzbek Cyrillic,¸1234567890  éöóêåíãø¢çõú\ô âàïðîëäæýÿ÷ñìèòüáþ.¨!"¹;%:?*()  ÉÖÓÊÅÍÃØ¡ÇÕÚ/Ô ÂÀÏÐÎËÄÆÝß×ÑÌÈÒÜÁÞ,
0000043f=kaz,kaz,Kazakh,(" ³  ,.     éöóêåíãøùçõú\ôûâàïðîëäæýÿ÷ñìèòüáþ¹)! ²  ;:     ÉÖÓÊÅÍÃØÙÇÕÚ/ÔÛÂÀÏÐÎËÄÆÝß×ÑÌÈÒÜÁÞ?
00000444=tat,tat,Tatar, 1234567890-=é óêåíãø çõ \ôûâàïðîëä ýÿ÷ñìèò áþ. !"¹;%:?*()_+É ÓÊÅÍÃØ ÇÕ /ÔÛÂÀÏÐÎËÄ Ýß×ÑÌÈÒ ÁÞ,´¥¸@#$[]{}öùúæ'ü<>¨ÖÙÚÆÜ

00000408=el,el,ÅëëçíéêÜ,`1234567890-=;òåñôõèéïð[]\áóäöãçîêë´'æ÷øùâíì,./~!@#$%^&*()_+:¡ÅÑÔÕÈÉÏÐ{}|ÁÓÄÖÃÇÎÊË¨"Æ×ØÙÂÍÌ<>?
00010408=el,el,ÅëëçíéêÜ (220),½1234567890'];òåñôõèéïð+}#áóäöãçîêë´¨æ÷øùâíì,.-±!"£$%&/()=?[:~ÅÑÔÕÈÉÏÐ*{@ÁÓÄÖÃÇÎÊË¨¡Æ×ØÙÂÍÌ;:_
00020408=el,el,ÅëëçíéêÜ (319),½1234567890'+·òåñôõèéïð[]²áóäöãçîêë´’æ÷øùâíì,.-±!"£$%¬/()=°*¯¦ÅÑÔÕÈÉÏÐ«»³ÁÓÄÖÃÇÎÊË¨‘Æ×ØÙÂÍÌ;:_
00060408=el,el,ÅëëçíéêÜ ðïëõôïíéêü,~1234567890-=;òåñôõèéïð[]\áóäöãçîêë´'æ÷øùâíì,./`!@#$%^&*()_+:¡ÅÑÔÕÈÉÏÐ{}|ÁÓÄÖÃÇÎÊË¨"Æ×ØÙÂÍÌ<>?

00000450=mn,mn,Mongolian,=¹-"¥:._,%?åùôöóæýíãø¿çêú\éûáºàõðîëäïÿ÷¸ñìèòüâþ+1234567890ÅÙÔÖÓÆÝÍÃØ¯ÇÊÚ|ÉÛÁªÀÕÐÎËÄÏß×¨ÑÌÈÒÜÂÞ
00000451=mn,mn,Mongolian,=¹-"¥:._,%?åùôöóæýíãø¿çêú\éûáºàõðîëäïÿ÷¸ñìèòüâþ+1234567890ÅÙÔÖÓÆÝÍÃØ¯ÇÊÚ|ÉÛÁªÀÕÐÎËÄÏß×¨ÑÌÈÒÜÂÞ

[EN]
Caps=ABCDEFGHIJKLMNOPQRSTUVWXYZÉÚÍÓÁÈÙÌÒÀ
Compliment=)]\
Laugh=qQ

[RU]
Caps=ÀÁÂÃÄÅ¨ÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞß
Compliment=)ú¸
Laugh=ýÝ

[UA]
Caps=ÉÖÓÊÅÍÃØÙÇÕ¯¥Ô²ÂÀÏÐÎËÄÆªß×ÑÌÈÒÜÁÞ
Compliment=¿´¯¥)`
Laugh=ºª

[BLR]
Caps=ÉÖÓÊÅÍÃØ¡ÇÕÔÛÂÀÏÐÎËÄÆÝß×ÑÌ²ÒÜÁÞ¨
Compliment=)'¸
Laugh=ýÝ

[DA]
Caps=QWERTYUIOPÅASDFGHJKLÆØZXCVBNMÕÃÑÁÉÝÚÍÓÈÙÌÒÀËÜÏÖÄÊÛÎÔÂ
Compliment=)]\
Laugh=qQ

[DE]
Caps=QWERTZUIOPÜASDFGHJKLÖÄYXCVBNMÊÛÎÔÂÉÚÍÓÁÝÈÙÌÒÀ
Compliment=)]\
Laugh=qQ

[IC]
Caps=ÖQWERTYUIOPÐASDFGHJKLZXCVBNMÆÞÊÛÎÔÂÈÙÌÒÀÉÝÚÍÓÁËÜÏÖÄÅ
Compliment=)]\
Laugh=qQ

[FR]
Caps=AZERTYUIOPQSDFGHJKLMWXCVBNÃÕÑÀÈÙÌÒÂÊÛÎÔÄËÜÏÖÇÉÚÍÓÁÝ
Compliment=)]\
Laugh=&

[IT]
Caps=QWERTYUIOPASDFGHJKLZXCVBNM
Compliment=)]\
Laugh=qQ

[SP]
Caps=QWERTYUIOPASDFGHJKLÑÇZXCVBNMÕÃÈÙÌÒÀÉÝÚÍÓÁÊÛÔÂËÜÖÄ
Compliment=)]\
Laugh=qQ

[NO]
Caps=QWERTYUIOPÅASDFGHJKLØÆZXCVBNMÉÝÚÍÓÁÕÃÑËÜÏÖÄÈÙÌÒÀÊÛÎÔÂ
Compliment=)]\
Laugh=qQ

[SE]
Caps=QWERTYUIOPÅASDFGHJKLÖÄZXCVBNMÕÃÑÉÝÚÍÓÁËÜÏÖÄÈÙÌÒÀÊÛÎÔÂ
Compliment=)]\
Laugh=qQ

[FI]
Caps=QWERTYUIOPÅASDFGHJKLÖÄZXCVBNMÕÃÑÉÝÚÍÓÁËÜÏÖÄÈÙÌÒÀÊÛÎÔÂ
Compliment=)]\
Laugh=qQ

[NL]
Caps=AZERTYUIOPQSDFGHJKLMWXCVBNÂÊÛÎÔÄËÜÏÖÁÉÝÚÍÓÀÈÙÌÒÃÕÑ
Compliment=)]\
Laugh=&

[PO]
Caps=QWERTYUIOPASDFGHJKLÇZXCVBNMËÜÏÖÄÉÝÚÍÓÁÕÃÑÈÙÌÒÀÊÛÎÔÂ
Compliment=)]\
Laugh=qQ

[BR]
Caps=QWERTYUIOPASDFGHJKLÇZXCVBNMÉÝÚÍÓÁÕÃÑÈÙÌÒÀÊÛÎÔÂËÜÏÖÄ
Compliment=)]\
Laugh=qQ

[HU]
Caps=QWERTZUIOPASDFGHJKLYXCVBNMÄÖÜÓÕÚÛÍÉÁÐ
Compliment=ÖÛ
Laugh=qQ

[BG]
Caps=ÓÅÈØÙÊÑÄÇÖÜßÀÎÆÃÒÍÂÌ×ÞÉÚÝÔÕÏÐËÁ
Compliment=)¹~
Laugh=û

[CZ]
Caps=QWERTZUIOPASDFGHJKLYXCVBNMÉÀÚÍÓÁŒÅÝÆÑÙÌØŽŠÏ¼ÈÒÐ£ÎÔÂÃÊ¥¯ÛÕËÜÖÄÞªÇ
Compliment=)]\
Laugh=qQ

[SK]
Caps=QWERTZUIOPASDFGHJKLYXCVBNMÉÀÚÍÓÁŒÅÝÆÑÙÌØŽŠÏ¼ÈÒ£ÎÔÂÃÊ¥¯ÛÕÜÖÄÞªÇ
Compliment=)]\
Laugh=qQ

[SI]
Caps=QWERTZUIOPŠÐŽASDFGHJKLÈÆYXCVBNMªÇËÜÖÄ£ÌØÏ¼ÒÎÔÂÃÙÊ¥¯ÉÀÚÍÓÁŒÅÝÑÛÕ
Compliment=)]\
Laugh=qQ

[RO]
Caps=QWERTZUIOPÃÎÂASDFGHJKLªÞYXCVBNMÐ£
Compliment=)]\
Laugh=qQ

[PL]
Caps=QWERTZUIOPASDFGHJKL£YXCVBNMÊ¥¯ÐÌØŽŠÏÈÒÎÔÂÃÙÉÀÚÍÓÁŒÝÆÑÛÕËÜÖÄ
Compliment=)'
Laugh=qQ

[ET]
Caps=QWERTYUIOPÜÕASDFGHJKLÖÄZXCVBNMÞÐÈÉÓÚÊÃÑÕ
Compliment=)]\
Laugh=qQ

[LV]
Caps=QWERTYUIOPASDFGHJKLZXCVBNMÇÛÎÕÂÐÌÍÏÞÈÒÉÓÚÊÃÑÜÖÄËÅÝ
Compliment=)]\
Laugh=qQ

[LT]
Caps=ÀÈÆËÁÐØÛÞQWERTYUIOPASDFGHJKLZXCVBNM
Compliment=)]\
Laugh=qQ

[AZ]
Caps=£ÓÊÅÍÃØÇÕÔÛÂÀÏÐÎËÄÆ×ÑÌÈÒÁ
Compliment=)]\
Laugh=qQ

[AZL]
Caps=QÜERTYUÝOPÖÐASDFGHJKLIZXCVBNMÇÞ
Compliment=)\
Laugh=Q

[UZB]
Caps=¨ÉÖÓÊÅÍÃØ¡ÇÕÚÔÂÀÏÐÎËÄÆÝß×ÑÌÈÒÜÁÞ
Compliment=)ú¸
Laugh=ýÝ

[KAZ]
Caps=²ÉÖÓÊÅÍÃØÙÇÕÚÔÛÂÀÏÐÎËÄÆÝß×ÑÌÈÒÜÁÞ
Compliment=)ú²
Laugh=ýÝ

[TAT]
Caps=ÉÓÊÅÍÃØÇÕÔÛÂÀÏÐÎËÄÝß×ÑÌÈÒÁÞ¥¨ÖÙÚÆÜ
Compliment=)¸ü
Laugh=ýÝ

[MN]
Caps=ÀÁÂÃÄÅ¨ÆÇÈÉÊËÌÍÎªÏÐÑÒÓ¯ÔÕÖ×ØÙÚÛÜÝÞß
Compliment=;)
Laugh=ýÝ
